### ISSUE TITLE
PPSSPP_libretro.dll

### ISSUE THREAD

**Issue by juri74** [HerbFargus/Portable-Game-Station#5]
hello this is not an issue only a help request please,
i noticed the file ppsspp_libretro.dll from retroarch is very old (from 2015)
however PPSSPP for windows latest version 1.3 is from 2016 (17/09/2016 about half year old)
do you know where i can find the updated version of the dll for use with retroarch please?
thanks

**Comment by HerbFargus** [comment]
I've released a new version with the latest stable PPSSPP core (though I wouldn't hold your breath on any advancements as that core hasn't seen much love)
